project_number: '24-004'
stockNIC_note:
- The receiver and/or source room had a volume exceeding 150 m3 (5,300 cu. ft.), and the absorption of the receiver and/or source room was greater than the maximum allowed per E336-16, Paragraph 9.4.1.2.
- The receiver and/or source room was not an enclosed space.
- The receiver and/or source room has a volume less than the minimum volume requirement of 25 m3 (883 cu. ft.).
- The receiver and/or source room has one or more dimensions less than the minimum requirement of 2.3 m (7.5 ft.).
ISR_ony_report: The receiver room had a volume less than the minimum volume requirement of 40 m3.
stockISR_notes:
- The receiver and/or source room had a volume exceeding 150 m3 (5,300 cu. ft.), and the absorption of the receiver room was greater than the maximum allowed per E1007-16, Paragraph 10.3.1 and 10.4.5.
- The receiver and/or source room was not an enclosed space.
- The receiver and/or source room has a volume less than the minimum volume requirement of 40 m3 (1413 cu. ft.).
- The receiver and/or source room has one or more dimensions less than the minimum requirement of 2.3 m (7.5 ft.).

standards_text:
- - "ASTC Test Procedure ASTM E336-16"
  - "Standard Test Method for Measurement of Airborne Sound Attenuation between Rooms in Buildings"
- - "STC Calculation	ASTM E413-16"
  - "Classification for Rating Sound Insulation"
- - "AIIC Test Procedure	ASTM E1007-14"
  - "Standard Test Method for Field Measurement of Tapping Machine Impact Sound Transmission Through Floor-Ceiling Assemblies and Associated Support Structure"
- - "IIC Calculation	ASTM E989-06(2012)"
  - "Standard Classification for Determination of Impact Insulation Class (IIC)"
- - "RT60 Test Procedure	ASTM E2235-04(2012)"
  - "Standard Test Method for Determination of Decay Rates for Use in Sound Insulation Test Methods"
- - "SPL Test Procedure	ANSI S1.11-2004"
  - "Specification for Octave-Band and Fractional-Octave-Band Analog and Digital Filters"


test_procedure_pg: >
  Determination of space-average sound pressure levels was performed via the
  manually scanned microphones techique, described in {{ standards_text[0][0] }},
  Paragraph 11.4.3.3. The source room was selected in accordance with ASTM
  E336-11 Paragraph 9.2.5, which states that "If a corridor must be used as one
  of the spaces for measurement of ATL or FTL, it shall be used as the source
  space."

flanking_text: >
  Flanking paths were not considered in this test. The test was conducted in
  accordance with ASTM E336-16, which states that "The test results are
  applicable only to the specific tested partition and the specific tested
  conditions."


RT_text: >
    To evaluate room absorption, 1 microphone was used to measure 4 decays at 4 locations around the receiving room for a total of 16 measurements, per {{ standards_text[4][0] }}

ASTC_results_ATverbage: >
  ' was calculated. The ASTC rating is based on Apparent Transmission Loss (ATL), and includes the effects of noise flanking. The ASTC reference contour is shown on the next page, and has been “fit” to the Apparent Transmission Loss values, in accordance with the procedure of'

NIC_results_NRverbage: >
  ' was calculated' was calculated. The NIC rating is based on Noise Reduction (NR), and includes the effects of noise flanking. The NIC reference contour is shown on the next page, and has been “fit” to the Apparent Transmission Loss values, in accordance with the procedure of'

Equip_type_list: >
  - "Sound Level Meter 1"
  - "Microphone Pre-Amp:"
  - "Microphone:"
  - "Calibrator:"
  - "Sound Level Meter 2"
  - "Microphone Pre-Amp:"
  - "Microphone:"
  - "Calibrator:"
  - "Amplified Loudspeakers"
  - "Noise Generator:"